version: "3"
services:
  game:
    build:
      context: .
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["./corewar.sh", "assets/champions/42.cor", "assets/champions/octobrerouge.cor", "assets/champions/abel.cor  assets/champions/fenix.cor"]
